name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18
      - uses: actions/checkout@v3
      - name: Install packages
        run: npm install
      - name: Vite build
        run: npm run build
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist/
